#!/usr/bin/env bash
cd $HOME/DRAGON
token="1781653097:AAFlBZK2CtoJdJ2TOQXh8Ayli4KQgvf66YE"
while(true) do
rm -fr ../.telegram-cli
if [ ! -f ./tg ]; then
echo "⩤━━━━━━𝐀𝐕𝐈𝐑𝐀━━━━━━⩥ ┉ ┉ ┉ ┉ ┉ ┉┉ ┉ ┉ ┉ ┉ ┉ ┉"
echo "TG IS NOT FIND IN FILES BOT"
echo "⩤━━━━━━𝐀𝐕𝐈𝐑𝐀━━━━━━⩥ ⩤━━━━━━𝐀𝐕𝐈𝐑𝐀━━━━━━⩥ ┉"
exit 1
fi
if [ ! $token ]; then
echo "⩤━━━━━━𝐀𝐕𝐈𝐑𝐀━━━━━━⩥ ⩤━━━━━━𝐀𝐕𝐈𝐑𝐀━━━━━━⩥ ┉ ┉"
echo -e "\e[1;36mTOKEN IS NOT FIND IN FILE vvvvvvInfo.lua \e[0m"
echo "⩤━━━━━━𝐀𝐕𝐈𝐑𝐀━━━━━━⩥ ┉ ┉ ┉ ┉┉ ┉ ┉ ┉ ┉ ┉ ┉ ┉┉ ┉"
exit 1
fi
echo -e "\033[38;5;208m"
echo -e "                                                  "
echo -e "\033[0;00m"
echo -e "\e[36m"
./tg -s ./DRAGON.lua -p PROFILE --bot=$token
done
